// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/material.dart';
import 'package:flutter_application_1/main.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
//import 'package:firebase_core/firebase_core.dart';
//import 'firebase_options.dart';

// ...
import 'firebase_options.dart';


Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(SmartSubway());
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSSgPUoDpZB164PivwY8-Zg957t6nTfmA',
    appId: '1:614310136265:web:d82fc5c31c350117eac018',
    messagingSenderId: '614310136265',
    projectId: 'project1-b950c',
    authDomain: 'project1-b950c.firebaseapp.com',
    storageBucket: 'project1-b950c.firebasestorage.app',
    measurementId: 'G-93ZDM0XHJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE2QrgBnAADf9tY1DsVZNk3bBlETEIiuY',
    appId: '1:614310136265:android:d540235e5d6cc552eac018',
    messagingSenderId: '614310136265',
    projectId: 'project1-b950c',
    storageBucket: 'project1-b950c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCYiSdqd6E5GYLc2zJyR2OHuIBtRcsctA',
    appId: '1:614310136265:ios:a3785b1bb48bf92beac018',
    messagingSenderId: '614310136265',
    projectId: 'project1-b950c',
    storageBucket: 'project1-b950c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCYiSdqd6E5GYLc2zJyR2OHuIBtRcsctA',
    appId: '1:614310136265:ios:a3785b1bb48bf92beac018',
    messagingSenderId: '614310136265',
    projectId: 'project1-b950c',
    storageBucket: 'project1-b950c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSSgPUoDpZB164PivwY8-Zg957t6nTfmA',
    appId: '1:614310136265:web:804cc6a259b32c75eac018',
    messagingSenderId: '614310136265',
    projectId: 'project1-b950c',
    authDomain: 'project1-b950c.firebaseapp.com',
    storageBucket: 'project1-b950c.firebasestorage.app',
    measurementId: 'G-S96Y8L7CS1',
  );

}