// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/material.dart';
import 'package:flutter_application_1/main.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
//import 'package:firebase_core/firebase_core.dart';
//import 'firebase_options.dart';

// ...
import 'firebase_options.dart';

import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(SmartSubway());
}


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw_wxQVe7v5Q8BkYADHF1tUZgAemaewOc',
    appId: '1:520527718838:web:08d5224f6f277a34bcf917',
    messagingSenderId: '520527718838',
    projectId: 'station-a1609',
    authDomain: 'station-a1609.firebaseapp.com',
    databaseURL: 'https://station-a1609-default-rtdb.firebaseio.com',
    storageBucket: 'station-a1609.firebasestorage.app',
    measurementId: 'G-CTNW5CR070',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrwTU3i6EIILEafiSqwAtrCQyVI6EA3Vg',
    appId: '1:520527718838:android:39fd28b8225ddffebcf917',
    messagingSenderId: '520527718838',
    projectId: 'station-a1609',
    databaseURL: 'https://station-a1609-default-rtdb.firebaseio.com',
    storageBucket: 'station-a1609.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC413sC1Rv06ykiH6qye4m1aZt8vraxX9g',
    appId: '1:520527718838:ios:651896cebe9fc3d6bcf917',
    messagingSenderId: '520527718838',
    projectId: 'station-a1609',
    databaseURL: 'https://station-a1609-default-rtdb.firebaseio.com',
    storageBucket: 'station-a1609.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC413sC1Rv06ykiH6qye4m1aZt8vraxX9g',
    appId: '1:520527718838:ios:651896cebe9fc3d6bcf917',
    messagingSenderId: '520527718838',
    projectId: 'station-a1609',
    databaseURL: 'https://station-a1609-default-rtdb.firebaseio.com',
    storageBucket: 'station-a1609.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw_wxQVe7v5Q8BkYADHF1tUZgAemaewOc',
    appId: '1:520527718838:web:084f085c294d68debcf917',
    messagingSenderId: '520527718838',
    projectId: 'station-a1609',
    authDomain: 'station-a1609.firebaseapp.com',
    databaseURL: 'https://station-a1609-default-rtdb.firebaseio.com',
    storageBucket: 'station-a1609.firebasestorage.app',
    measurementId: 'G-4FTK6BLDSC',
  );

}