/*// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjyPanF_1IFUYJ4TprAebh6tsuZcKN7xM',
    appId: '1:561653222807:web:08e57f65efe7d79b9248d2',
    messagingSenderId: '561653222807',
    projectId: 'mju-teamproject-fa7ee',
    authDomain: 'mju-teamproject-fa7ee.firebaseapp.com',
    storageBucket: 'mju-teamproject-fa7ee.firebasestorage.app',
    measurementId: 'G-98JG49JPCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXFEQ_fURIB_4JxX9rfdcYmjF1mKS7LKw',
    appId: '1:561653222807:android:e4bb5ce4ea1e6e649248d2',
    messagingSenderId: '561653222807',
    projectId: 'mju-teamproject-fa7ee',
    storageBucket: 'mju-teamproject-fa7ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9FZLg00BOt776D9CRSALGcwSML1myivw',
    appId: '1:561653222807:ios:ae0fe881e40f38419248d2',
    messagingSenderId: '561653222807',
    projectId: 'mju-teamproject-fa7ee',
    storageBucket: 'mju-teamproject-fa7ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjyPanF_1IFUYJ4TprAebh6tsuZcKN7xM',
    appId: '1:561653222807:web:e696330d791010269248d2',
    messagingSenderId: '561653222807',
    projectId: 'mju-teamproject-fa7ee',
    authDomain: 'mju-teamproject-fa7ee.firebaseapp.com',
    storageBucket: 'mju-teamproject-fa7ee.firebasestorage.app',
    measurementId: 'G-SXTNF35B7D',
  );
}*/
